name: CI
on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Install Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: "2.0.5"
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code smells
        run: flutter analyze .
      - name: Analyze code style
        run: |
          if [[ $(dartfmt ./ -n) ]]; then
            echo "Failed check style"
            echo $(dartfmt ./ -n)
            exit 1
          else
            exit 0
          fi
      - name: Run tests
        run: flutter test
